require 'settings.common.base'
require 'settings.common.keymap'
require 'settings.common.data'
require 'settings.common.filetype'
require 'settings.common.colors'
require 'settings.common.window'
require 'settings.common.gui'
